from . import (
    auth,
    name_query,
    personal_disease,
    manager_esma,
    manager_verse,
    spiritual_issues,
    name_coaching,
    disease_element,
    personal_manager_esma,
    couple_compatibility,
    disease_organ,
    magic_analysis,
    disease_prone,
    comprehensive_analysis,
    financial_blessing,
)
