services:
  - type: web
    name: ebced-api
    env: python
    rootDirectory: ebced/backend
    buildCommand: |
      mkdir -p data
      cp ../data/data.xlsx data/
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: DATABASE_URL
        sync: false # Bu değişken Render dashboard'dan ayarlanacak
      - key: JWT_SECRET_KEY
        sync: false # Bu değişken Render dashboard'dan ayarlanacak
    cors:
      origins:
        - https://ebced.vercel.app # Frontend'in Vercel URL'i
        - http://localhost:5173 # Geliştirme ortamı için 